### PR TITLE
Allow users to provide their own OAI specs.

### LINKED ISSUE #54: Support alternative swagger.json file
We need to support the K8S metrics-server API (https://github.com/kubernetes-incubator/metrics-server) in our implementation.

To do this I need to fork the Kazan repo to make the following changes:
 - Use a different `swagger.json` which included the metrics-server endpoints
 - Add two lines to `Kazan.Codegen.Naming` to map the metrics namespace

(https://github.com/chazsconi/kazan/commit/cd923bcab39a0a593b628ddb7d06fc87d694c6e9#diff-1856cab08f35cbaee3b304822e1699c4)

It would be nice if these two things could be set via the configuration.

Additionally I also had to manually change the `swagger.json` so the `window` field is a string rather than a `Duration` cause a crash when decoding, but this is really a different issue, and I'm not sure how to fix it properly.

https://github.com/chazsconi/kazan/commit/0e44c4ec6ca5f691443bad766f83c9147f9d2812

### PR DESCRIPTION
**Pull request by obmarg**
Some users of Kazan are using k8s extensions that add new APIs & models
to k8s.  Currently the only way to get Kazan to know about these new
APIs and models is to fork the library and update the swagger
appropriately.

This commit updates kazan with two new configuration options:

- `oai_spec` allows the user to provide a different open API spec file
  to compile the library with.
- `oai_name_mappings` allows the user to add extra mappings from open
api specification names to elixir modules.

Fixes #54

### CODE REVIEW

**Comment by obmarg** [comment]
I need to figure out how best to document this functionality...

**Comment by chazsconi** [comment]
Looks good and it works well for me.  However, a lot of the commits are automatic ones made by the Elixir formatter which would probably be better separated into a different commit/PR.

**Comment by coryodaniel** [comment]
Can you provide an example of a custom module?

**Comment by chazsconi** [comment]
@obmarg Do you think you will be able to merge this soon?

**Comment by obmarg** [comment]
@chazsconi sure, kinda forgot about this 🤦‍♂️

**Comment by chazsconi** [comment]
@obmarg Thanks!

**Comment by obmarg** [comment]
@chazsconi no problem.  will try and push out a release once I get home tonight

**Comment by obmarg** [comment]
@chazsconi this one's out now too

**Pull request merged**
