### PR TITLE
1.7 upgrade

### PR DESCRIPTION
**Pull request by jeremytregunna**
This pull request brings API support up to 1.7, and as such involves some breaking changes that need close scrutiny.

One area we'd (@jeremytregunna and @thoughtmanifest) like feedback on is how we've handled the kube configuration changes in this PR. We're not sure if it matches the original intent, and are open to changes here.

### CODE REVIEW

**Comment by jeremytregunna** [comment]
@obmarg I'd also like to suggest some changes that aren't in this pull request: Namely as they relate to CI. Seems to be set up to pull versions of elixir that have problems (i.e., 1.4.0-rc.1 isn't available on hex anymore).

**Comment by obmarg** [comment]
@jeremytregunna updated the travis versions in #5 if you want to pull that in.

**Comment by obmarg** [comment]
I'm not too into the module names that we're using for models with the latest OAI specs from Kube - they seem a bit verbose.  To pick one example from the tests, "Kazan.Models.Io.K8s.Apimachinery.Pkg.Apis.Meta.V1.OwnerReference" seems a bit ridiculous.

I'm wondering if it might be worth transforming them a bit more before using them as module names.

From looking at what we generate there seems to be a few categories:

1. `Io.K8s.Kubernetes.Pkg.Api.V1.*`
2. `Io.K8s.Kubernetes.Pkg.Apis.*`
3. `Io.K8s.Apimachinery.*`
4. `Io.K8s.Kube-aggregator.`

I'm wondering if it'd be worth transforming the names into the following:

1. `Kazan.Models.Api.*`
2. `Kazan.Models.Apis.*`
3. `Kazan.Models.Apimachinery.*` (side note: is it worth special casing this to transform Apimachinery into ApiMachinery?)
4. `Kazan.Models.KubeAggregator` (`-` isn't valid in an Elixir module name, so we need to get rid of it.  It doesn't complain, but does break ExDoc and is pretty hard to call into)

Thoughts?

**Comment by obmarg** [comment]
I've merged some of the commits that @izaakschroeder did on his 1.6 branch into master.  I see you've also pulled some of this work in, but I wanted to pull the commits direct from his branch so he gets properly credited in the git history.

Do you mind rebasing (or merging) on top of master?  Apologies for the conflicts.

**Comment by thoughtmanifest** [comment]
@obmarg I've updated the PR with the changes you've merged. 

As far as module names are concerned, I'm not married to the verbose names, but they do have the simplicity of clearly mapping back to the OAI doc which makes it easier to look up the specifics about a given model. There may be some benefit to providing a shorter alias, but I'd want to maintain the easy lookup, so they should be explicit enough to do that.

**Comment by jeremytregunna** [comment]
Just a comment about the test failure that is showing as of the time I posted this, looked into it, looks like the test process was killed by some outside supervisor. Rerunning it probably will pass like the other runs did. https://travis-ci.org/obmarg/kazan/jobs/271794668

**Comment by obmarg** [comment]
Around the issue of names, the verbose versions of the names also make the documentation for kazan fairly unusable:

image

The docs generated with shorter names are _better_, although some of the names are still a bit too long to fit into the sidebar:

image

I can see some value in being able to link the models back to their definitions in the OAI spec but I'm not sure whether it needs to be at the expense of documentation & general usability of the library...  I'm considering whether to just add the original OAI name to the documentation of each model, or perhaps a function on each model module that you can call to get the spec...

RE: the failing test - I've retried it a couple of times now, but that failure seems pretty consistent...

**Comment by thoughtmanifest** [comment]
Hmm, I like both of those ideas. I think the documentation should work both ways. For instance, I should be able to look at the kazan doc for a specific function and find the full OAI name. I should also be able to input the full OAI name somewhere and get back out the function that matches. If both of those are available, then I think you could alias all the way down to `<lib>.<logical container(s)>.<versioning info>.<elixirified OAI function name>`, e.g. `Kazan.Apis.CoreV1.list_pod_for_all_namespaces!` Even versioning info could be removed if there are no collisions on function name.

So, I'd want to be able to call 
```
iex> h Kazan.Apis.CoreV1.list_pod_for_all_namespaces!
OAI operationId: listCoreV1PodForAllNamespaces
... 
``` 
and similarly call 
```
iex> lookup("listCoreV1PodForAllNamespaces")
[
  Kazan.Apis.CoreV1.list_pod_for_all_namespaces!/0,
  Kazan.Apis.CoreV1.list_pod_for_all_namespaces!/1,
  Kazan.Apis.CoreV1.list_pod_for_all_namespaces/0,
  Kazan.Apis.CoreV1.list_pod_for_all_namespaces/1
]
```

**Comment by jeremytregunna** [comment]
@obmarg We also discovered that the autogenerated names break distillery on Erlang 19. As in, distillery fails due a limitation of `erl_tar` to handle module names that are 100 bytes or less in length. For reference: bitwalker/distillery#231

**Comment by obmarg** [comment]
Ok, so sounds like we might need to do _something_ to work around the
distillery issue at least. Unless it's fixed reasonably soon anyway.

I'm away on vacation right now. Will be back in just over a week, and will
deal with this then.

**Comment by jeremytregunna** [comment]
@obmarg yeah if we can figure out how we'd like the module names to appear in short form, we can get on making those changes to this branch. That should resolve that distillery issue by bringing all module names under 100 bytes. Anyway, we'll chat when you're back. We're at the end of a release cycle so time has been limited this past week. My apologies.

**Comment by chazsconi** [comment]
Hi @obmarg Is there any chance of getting this merged soon?  There's a few features in 1.7 that we need to use.

Thanks

**Comment by obmarg** [comment]
@chazsconi hoping to get this out extremely soon.

@jeremytregunna @thoughtmanifest Sorry about how long I have slept on this PR.  I've not been able to dedicate any time at all to programming outside of work for some time.

I've made quite a few changes on master since this PR was made - merging in the work from #2, adding ways to lookup things by operation ID (as we discussed in this PR) and shortening the module names.  I wanted to get all that stuff out and a release with the kube 1.6 spec made before merging in this 1.7 stuff.  But, now it's all ready to go.

I'm probably going to end up rebasing the changes in this PR onto master myself - hope you don't mind, but this has sat about for too long.

**Comment by obmarg** [comment]
There were a _ton_ of awkward merge conflicts in this, so I've ended up rewriting history a bit.  But the work for this is now on master.

Thanks for the contributions @jeremytregunna & @thoughtmanifest

**Comment by obmarg** [comment]
This has now been released as part of v0.5.0

**Pull request closed without merging**
